// Build a self-hosted font bundle from Fontsource packages.
// - Copies the woff2 shards (with their unicode-range splits) into public/fonts/
// - Concatenates the @font-face rules into src/styles/fonts.css (generated)
// - Rewrites url(./files/x.woff2) -> url(/fonts/x.woff2)
// - Strips the " Variable" suffix from font-family so existing CSS keeps working
//   (e.g. "Noto Sans JP Variable" -> "Noto Sans JP")
//
// Re-run with `pnpm build:fonts` after changing the package list.

import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const fontsDir = join(root, "public", "fonts");
const outCss = join(root, "src", "styles", "fonts.css");

// Each entry maps a Fontsource package to the CSS files to bundle.
// - scope: "@fontsource" (static) or "@fontsource-variable" (variable axis)
// - cssFiles: explicit list; for static families this selects the weights.
const packages = [
  {
    scope: "@fontsource-variable",
    name: "albert-sans",
    cssFiles: ["index.css"],
  },
  {
    scope: "@fontsource-variable",
    name: "noto-sans-jp",
    cssFiles: ["index.css"],
  },
  {
    scope: "@fontsource-variable",
    name: "noto-sans-tc",
    cssFiles: ["index.css"],
  },
  {
    scope: "@fontsource-variable",
    name: "noto-sans-sc",
    cssFiles: ["index.css"],
  },
];

mkdirSync(fontsDir, { recursive: true });

// public/fonts also holds hand-placed fonts (Riichi-Mahjong, Paper Mono) that
// are not produced here, so only remove woff2 matching our package prefixes
// instead of wiping the whole directory.
const managedPrefixes = packages.map(({ name }) => name);
for (const file of readdirSync(fontsDir)) {
  if (managedPrefixes.some((prefix) => file.startsWith(prefix))) {
    rmSync(join(fontsDir, file));
  }
}

let combined = `/* Self-hosted fonts generated by scripts/build-fonts.mjs - do not edit by hand. */\n`;
combined += `/* Run \`pnpm build:fonts\` to regenerate. */\n\n`;

let copied = 0;
for (const { scope, name, cssFiles } of packages) {
  const pkgDir = join(root, "node_modules", scope, name);

  for (const cssFile of cssFiles.filter((f) => existsSync(join(pkgDir, f)))) {
    let css = readFileSync(join(pkgDir, cssFile), "utf8");

    // Copy every referenced woff2 into public/fonts/.
    for (const m of css.matchAll(/url\(\.\/files\/([^)]+\.woff2)\)/g)) {
      const file = m[1];
      copyFileSync(join(pkgDir, "files", file), join(fontsDir, file));
      copied++;
    }

    // Drop woff fallbacks (modern browsers all support woff2), rewrite paths,
    // and strip the " Variable" family suffix.
    css = css
      .replace(/,\s*url\(\.\/files\/[^)]+\.woff\)\s*format\('woff'\)/g, "")
      .replace(/url\(\.\/files\//g, "url(/fonts/")
      .replace(/font-family:\s*'([^']+?) Variable'/g, "font-family: '$1'");

    combined += `/* ${name} — ${cssFile} */\n${css.trim()}\n\n`;
  }
}

mkdirSync(dirname(outCss), { recursive: true });
writeFileSync(outCss, combined);
console.log(`Copied ${copied} woff2 files to public/fonts/`);
console.log(`Wrote ${outCss}`);
